site_name: Monitor Hierarchy Lab
site_url: http://maximo-lab.monitordemo4.ibmmam.com/
site_author: Mike Lamb
site_description: "Monitor Hierarchy Lab"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site/mas_monitor_hierarchy

nav:
  - Get back to Maximo Labs: /
  - Monitor Labs:
    - Welcome to the Monitor Labs: index.md
    - Get Started: getting_started.md
    - Pre-Requisites: prereqs.md
    - Exercises:
        - 1. Create hierarchy: create_hierarchy.md
        - 2. Assign devices: assign_devices.md
        - 3. Create dashboards: create_dashboards.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition