site_name: Contribute to IBM Maximo Labs
site_url: http://maximo-lab.monitordemo4.ibmmam.com/
site_author: Jan Ekstr√∏m & Contributors
site_description: "How to contribute to the IBM Maximo hands on abs"
site_dir: ../../site/contribute

nav:
  - Get back to Maximo Labs: /
  - Contribute:
    - Welcome to contribute: index.md
    - Get started: getting_started.md
    - Pre-Requisites: prereqs.md
  - Exercises:
    - Add content: add_content.md
    - Create new lab: create_new.md
    - Deploy to IBM Cloud: deploy.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: copyright.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition

