site_name: Contribute to IBM Maximo Labs
site_url: https://ibm.github.io/maximo-labs/
site_author: Jan Ekstr√∏m & Contributors
site_description: "How to contribute to the IBM Maximo hands on abs"
site_dir: ../../site/contribute

nav:
  - Get back to Maximo Labs: ..
  - Contribute:
    - Welcome to contribute: index.md
    - Get started: get_started.md
    - Pre-Requisites: prereqs.md
  - Tasks:
    - Add content: add_content.md
    - Create new lab: create_new.md
    - Deploy to IBM Cloud: deploy.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition

