site_name: IBM Maximo Labs
site_url: https://ibm.github.io/maximo-labs/
site_author: Carlos Ferreira, Jan Ekstr√∏m & Contributors
site_description: "IBM Maximo Hands-on Lab"
site_dir: ../../site

nav:
  - Welcome to the Maximo Labs: index.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: copyright.md


theme:
  name: readthedocs
  analytics:
    gtag: G-EGH6ZGZ8CT
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - extra.css

extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.js
  - js/clipboard.js
  - js/extra.js
