site_name: IBM Maximo Labs
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Carlos Ferreira & Contributors
site_description: "IBM Maximo Hands on Lab"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site


nav:
  - Welcome to the Maximo Labs: index.md
  - About: about.md

theme: readthedocs

markdown_extensions:
  - attr_list
  - admonition