site_name: MAS Monitor Connect Lab
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Mike Lamb
site_description: "MAS Monitor Connect Lab"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site/mas_monitor_connect

nav:
  - Get back to Maximo Labs: /
  - MAS Monitor Connect Lab:
    - Welcome: index.md
    - Pre-Requisites: prereqs.md
    - Exercises:
        - 1. Setup mobile device in Monitor: setup_device.md
        - 2. Connect mobile device to Monitor: connect_device.md
        - 3. Verify event data is being sent and persisted in Monitor: verify_data.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition