site_name: MAS Monitor Connect Lab
site_url: https://ibm.github.io/maximo-labs/
site_author: Mike Lamb
site_description: "MAS Monitor Connect Lab"
site_dir: ../../site/mas_monitor_connect

nav:
  - Get back to Maximo Labs: ..
  - MAS Monitor Connect Lab:
    - Welcome: index.md
    - Pre-Requisites: prereqs.md
    - Exercises:
        - 1. Setup mobile device in Monitor: setup_device.md
        - 2. Connect mobile device to Monitor: connect_device.md
        - 3. Verify event data is being sent and persisted in Monitor: verify_data.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright


theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition