site_name: Monitor Node-RED CSV Importer Lab
site_url: https://ibm.github.io/maximo-labs/
site_author: Jan Ekstr√∏m & Contributors
site_description: "Maximo Monitor Node-RED CSV Importer Hands on Lab"
site_dir: ../../site/monitor_nodered_csv_importer_1.0

nav:
  - Get back to Maximo Labs: ..
  - Monitor Node-RED CSV Importer Lab:
    - Welcome: index.md
    - Pre-Requisites: prereqs.md
  - Exercises:
    - 1. Setup environment: setup.md
    - 2. Get Node-RED script: get_script.md
    - 3. Adjust and run Node-RED script: adjust_script.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - ../css/extra.css

extra_javascript:
  - ../js/popper.min.js
  - ../js/tippy-bundle.umd.js
  - ../js/clipboard.js
  - ../js/extra.js
