site_name: APM Overview 8.2 Labs
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Carlos Ferreira & Contributors
site_description: "Maximo Monitor, Health and Predict Overview Hands on Lab"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site/apm_fs21

nav:
  - Get back to Maximo Labs: /
  - APM Overview 8.2 Labs:
    - Welcome to the Maximo Monitor, Health and Predict Overview Lab: index.md
    - Get Started: getting_started.md
    - Pre-Requisites: prereqs.md
    - Exercises:
        - 1. Remotely Monitor the Operational Status of Assets: monitor_assets.md
        - 2. Manage Asset Servicing: manage_assets.md
        - 3. Manage Asset Health: asset_health.md
        - 4. Predict Asset Performance : predict_performance.md
    - Demo Steps:
        - 1. Monitor: demo-monitor.md
        - 2. Manage - Mobile: demo-mobile.md
        - 3. Health: demo-health.md
        - 4. Health - Predict: demo-health-predict.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition