site_name: MAS 8.9 Deployment Lab
site_url: https://ibm.github.io/maximo-labs/
site_author: Arif Ali & Contributors
site_description: "MAS 8.9 Deployment Lab"
site_dir: ../../site/ocp_8.9

nav:
  - Get back to Maximo Labs: ..
  - MAS 8.9 Deployment Labs:
    - Welcome to the Lab: index.md
    - Get Started: getting_started.md
    - Pre-Requisites: prereqs.md
    - Exercises:
        - 1. Logistics: logistics.md
        - 2. Infrastructure: technical.md
        - 3. Preparation: preparation.md
        - 4. Deployment: deployment.md
        - 5. Post-deployment: post_deployment.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - ../css/extra.css

extra_javascript:
  - ../js/popper.min.js
  - ../js/tippy-bundle.umd.js
  - ../js/clipboard.js
  - ../js/extra.js
